apiVersion: skaffold/v4beta11
kind: Config
build:
  local:
    push: true
  artifacts:
    - image: logandevs/auth
      context: auth
      sync:
        manual:
          - src: 'src/**.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: logandevs/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: logandevs/tickets
      context: tickets
      sync:
        manual:
          - src: 'src/**.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: logandevs/orders
      context: orders
      sync:
        manual:
          - src: 'src/**.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: logandevs/expiration
      context: expiration
      sync:
        manual:
          - src: 'src/**.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
