apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: us.gcr.io/stubhub-app-dev-430119/auth
      context: auth
      sync:
        manual:
          - src: src/**.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: stubhub-app-dev-430119
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
